### ISSUE TITLE
[Bug] ML's context menu missing from channel context menu

### ISSUE THREAD

**Issue by surya27895** [Davilarek/MessageLoggerV2-fixed#2]
Hi, thanks for this amazing forks!!
I try to whitelisting server channel like old ones and surprisely it still can do and works flawlessly
then I think it will be awesome if you can add context menu when right click on server channel instead of add it manualy with edit the config file.

**Comment by Davilarek** [comment]
Hello, thanks for using the fixed version.
Do you mean whitelisting specific channels instead of servers?
I'm not sure I understand correctly...

**Comment by XspeedPL** [comment]
Sounds like whitelisting via context menu actions isn't working for him?
Post logs

**Comment by surya27895** [comment]
> Sounds like whitelisting via context menu actions isn't working for him? Post logs

yes this is what i mean, i think that features is gone

here my screenshot from context menu at channel right click

![image](https://user-images.githubusercontent.com/22859567/226384564-0d667a5e-36a2-42cd-b6bd-3df821049c1d.png)

i'm not to sure what logs you mean, but if it mean from console here it is
```
VM75 renderer_init.js:33 The vm module of Node.js is deprecated in the renderer process and will be removed.
o._load @ VM75 renderer_init.js:33
99ed9d0d194d4628b2e9.js:151 Unsupported Locale en-GB
(anonymous) @ 99ed9d0d194d4628b2e9.js:151
99ed9d0d194d4628b2e9.js:151 Unsupported Locale en
(anonymous) @ 99ed9d0d194d4628b2e9.js:151
99ed9d0d194d4628b2e9.js:151 [Spellchecker] sh is not a valid locale.
(anonymous) @ 99ed9d0d194d4628b2e9.js:151
4b9659d7526aa3979710.js:103 Uncaught (in promise) Error: Cannot find module './notosans-400-normalitalic.woff2'
    at 4b9659d7526aa3979710.js:103
    at async Promise.all (index 3)
99ed9d0d194d4628b2e9.js:151 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 5/13/2022 10:00 -0800, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (https://discord.com/assets/4b9659d7526aa3979710.js:1350:330)
    at Bn (https://discord.com/assets/4b9659d7526aa3979710.js:1376:696)
    at Wn (https://discord.com/assets/4b9659d7526aa3979710.js:1379:356)
    at Zn (https://discord.com/assets/4b9659d7526aa3979710.js:1379:199)
    at Yn (https://discord.com/assets/4b9659d7526aa3979710.js:1378:886)
    at Kn (https://discord.com/assets/4b9659d7526aa3979710.js:1379:697)
    at zn (https://discord.com/assets/4b9659d7526aa3979710.js:1379:731)
    at o (https://discord.com/assets/4b9659d7526aa3979710.js:1346:961)
    at Object.408481 (https://discord.com/assets/cb55214b1d3b43b20ce4.js:21:346)
    at l (https://discord.com/assets/7d4f690bcfff9ab0d122.js:1:154)
    at Object.558820 (https://discord.com/assets/cb55214b1d3b43b20ce4.js:14:240)
    at l (https://discord.com/assets/7d4f690bcfff9ab0d122.js:1:154)
    at Object.308739 (https://discord.com/assets/cb55214b1d3b43b20ce4.js:2:331)
    at l (https://discord.com/assets/7d4f690bcfff9ab0d122.js:1:154)
    at Object.173242 (https://discord.com/assets/79226e60c979f811ea95.js:353:631)
    at l (https://discord.com/assets/7d4f690bcfff9ab0d122.js:1:154)
    at Module.409169 (https://discord.com/assets/543d7306ae64ba5afce1.js:42:174)
    at Function.l (https://discord.com/assets/7d4f690bcfff9ab0d122.js:1:154)
(anonymous) @ 99ed9d0d194d4628b2e9.js:151
99ed9d0d194d4628b2e9.js:151 [DEPRECATED] Please use `subscribeWithSelector` middleware
(anonymous) @ 99ed9d0d194d4628b2e9.js:151
99ed9d0d194d4628b2e9.js:151 [NativeDispatchUtils] Tried getting Dispatch instance before instantiated
(anonymous) @ 99ed9d0d194d4628b2e9.js:151
99ed9d0d194d4628b2e9.js:151 [BetterDiscord] [WebpackModules~getModule] Module filter threw an exception. m => m?.toString().includes("numpad plus") TypeError: m?.toString is not a function
    at modules__WEBPACK_IMPORTED_MODULE_1__.WebpackModules.getModule.searchExports (betterdiscord://plugins/0PluginLibrary.plugin.js:5436)
    at <anonymous>:4:48303
    at Function.getModule (<anonymous>:4:49060)
    at Object.getModule (<anonymous>:4:401489)
    at Function.getModule (betterdiscord://plugins/0PluginLibrary.plugin.js:2986)
    at Object../src/ui/settings/types/keybind.js (betterdiscord://plugins/0PluginLibrary.plugin.js:5436)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6166)
    at Object../src/ui/settings/index.js (betterdiscord://plugins/0PluginLibrary.plugin.js:4798)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6166)
    at Object../src/ui/ui.js (betterdiscord://plugins/0PluginLibrary.plugin.js:6123)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6166)
    at Object../src/modules/pluginupdater.js (betterdiscord://plugins/0PluginLibrary.plugin.js:1715)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6166)
    at Object../src/structs/plugin.js (betterdiscord://plugins/0PluginLibrary.plugin.js:3588)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6166)
    at Object../src/structs/structs.js (betterdiscord://plugins/0PluginLibrary.plugin.js:3816)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6166)
    at Object../src/modules/domtools.js (betterdiscord://plugins/0PluginLibrary.plugin.js:659)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6166)
    at Object../src/modules/modules.js (betterdiscord://plugins/0PluginLibrary.plugin.js:1570)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6166)
    at eval (betterdiscord://plugins/0PluginLibrary.plugin.js:6213)
    at eval (betterdiscord://plugins/0PluginLibrary.plugin.js:6320)
    at eval (betterdiscord://plugins/0PluginLibrary.plugin.js:6323)
    at Object.requireAddon (<anonymous>:4:37871)
    at Object.loadAddon (<anonymous>:4:8814)
    at Object.loadAddon (<anonymous>:4:35543)
    at Object.loadAllAddons (<anonymous>:4:11288)
    at Object.initialize (<anonymous>:4:5710)
    at Object.initialize (<anonymous>:4:34738)
    at Object.startup (<anonymous>:4:392305)
(anonymous) @ 99ed9d0d194d4628b2e9.js:151
99ed9d0d194d4628b2e9.js:151 [BetterDiscord] [WebpackModules~getModule] Module filter threw an exception. m => m?.toString().includes("keyCode") && m?.toString().includes("BROWSER") TypeError: m?.toString is not a function
    at modules__WEBPACK_IMPORTED_MODULE_1__.WebpackModules.getModule.searchExports (betterdiscord://plugins/0PluginLibrary.plugin.js:5437)
    at <anonymous>:4:48303
    at Function.getModule (<anonymous>:4:49060)
    at Object.getModule (<anonymous>:4:401489)
    at Function.getModule (betterdiscord://plugins/0PluginLibrary.plugin.js:2986)
    at Object../src/ui/settings/types/keybind.js (betterdiscord://plugins/0PluginLibrary.plugin.js:5437)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6166)
    at Object../src/ui/settings/index.js (betterdiscord://plugins/0PluginLibrary.plugin.js:4798)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6166)
    at Object../src/ui/ui.js (betterdiscord://plugins/0PluginLibrary.plugin.js:6123)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6166)
    at Object../src/modules/pluginupdater.js (betterdiscord://plugins/0PluginLibrary.plugin.js:1715)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6166)
    at Object../src/structs/plugin.js (betterdiscord://plugins/0PluginLibrary.plugin.js:3588)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6166)
    at Object../src/structs/structs.js (betterdiscord://plugins/0PluginLibrary.plugin.js:3816)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6166)
    at Object../src/modules/domtools.js (betterdiscord://plugins/0PluginLibrary.plugin.js:659)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6166)
    at Object../src/modules/modules.js (betterdiscord://plugins/0PluginLibrary.plugin.js:1570)
    at __webpack_require__ (betterdiscord://plugins/0PluginLibrary.plugin.js:6166)
    at eval (betterdiscord://plugins/0PluginLibrary.plugin.js:6213)
    at eval (betterdiscord://plugins/0PluginLibrary.plugin.js:6320)
    at eval (betterdiscord://plugins/0PluginLibrary.plugin.js:6323)
    at Object.requireAddon (<anonymous>:4:37871)
    at Object.loadAddon (<anonymous>:4:8814)
    at Object.loadAddon (<anonymous>:4:35543)
    at Object.loadAllAddons (<anonymous>:4:11288)
    at Object.initialize (<anonymous>:4:5710)
    at Object.initialize (<anonymous>:4:34738)
    at Object.startup (<anonymous>:4:392305)
(anonymous) @ 99ed9d0d194d4628b2e9.js:151
99ed9d0d194d4628b2e9.js:151 [BunnyLib] 
Stealing your token... 
1..
2...
3....
Done.
(anonymous) @ 99ed9d0d194d4628b2e9.js:151
99ed9d0d194d4628b2e9.js:151 [BetterTypingUsers] Failed to create 1337 channel TypeError: CChannel is not a constructor
    at eval (betterdiscord://plugins/BetterTypingUsers.plugin.js:147)
    at buildPlugin (betterdiscord://plugins/BetterTypingUsers.plugin.js:151)
    at eval (betterdiscord://plugins/BetterTypingUsers.plugin.js:512)
    at eval (betterdiscord://plugins/BetterTypingUsers.plugin.js:513)
    at Object.requireAddon (<anonymous>:4:37871)
    at Object.loadAddon (<anonymous>:4:8814)
    at Object.loadAddon (<anonymous>:4:35543)
    at Object.loadAllAddons (<anonymous>:4:11288)
    at Object.initialize (<anonymous>:4:5710)
    at Object.initialize (<anonymous>:4:34738)
    at Object.startup (<anonymous>:4:392305)
(anonymous) @ 99ed9d0d194d4628b2e9.js:151
99ed9d0d194d4628b2e9.js:151 [BetterTypingUsers] Failed to get TypingUsers! TypeError: WrappedTypingUsers is not a constructor
    at eval (betterdiscord://plugins/BetterTypingUsers.plugin.js:156)
    at buildPlugin (betterdiscord://plugins/BetterTypingUsers.plugin.js:161)
    at eval (betterdiscord://plugins/BetterTypingUsers.plugin.js:512)
    at eval (betterdiscord://plugins/BetterTypingUsers.plugin.js:513)
    at Object.requireAddon (<anonymous>:4:37871)
    at Object.loadAddon (<anonymous>:4:8814)
    at Object.loadAddon (<anonymous>:4:35543)
    at Object.loadAllAddons (<anonymous>:4:11288)
    at Object.initialize (<anonymous>:4:5710)
    at Object.initialize (<anonymous>:4:34738)
    at Object.startup (<anonymous>:4:392305)
(anonymous) @ 99ed9d0d194d4628b2e9.js:151
99ed9d0d194d4628b2e9.js:151 [BetterTypingUsers] Failed to get ComponentDispatch TypeError: Cannot read property 'ComponentDispatch' of undefined
    at eval (betterdiscord://plugins/BetterTypingUsers.plugin.js:165)
    at buildPlugin (betterdiscord://plugins/BetterTypingUsers.plugin.js:169)
    at eval (betterdiscord://plugins/BetterTypingUsers.plugin.js:512)
    at eval (betterdiscord://plugins/BetterTypingUsers.plugin.js:513)
    at Object.requireAddon (<anonymous>:4:37871)
    at Object.loadAddon (<anonymous>:4:8814)
    at Object.loadAddon (<anonymous>:4:35543)
    at Object.loadAllAddons (<anonymous>:4:11288)
    at Object.initialize (<anonymous>:4:5710)
    at Object.initialize (<anonymous>:4:34738)
    at Object.startup (<anonymous>:4:392305)
(anonymous) @ 99ed9d0d194d4628b2e9.js:151
99ed9d0d194d4628b2e9.js:151 TypeError: Cannot read property 'Looks' of undefined
    at eval (betterdiscord://plugins/1XenoLib.plugin.js:2085)
    at t.Spring (4b9659d7526aa3979710.js:272)
    at Sa (4b9659d7526aa3979710.js:1651)
    at yu (4b9659d7526aa3979710.js:1705)
    at Oc (4b9659d7526aa3979710.js:1698)
    at Ic (4b9659d7526aa3979710.js:1698)
    at hc (4b9659d7526aa3979710.js:1697)
    at uc (4b9659d7526aa3979710.js:1694)
    at Fo (4b9659d7526aa3979710.js:1634)
    at nc (4b9659d7526aa3979710.js:1692)
    at ts (4b9659d7526aa3979710.js:1656)
    at listener (betterdiscord://plugins/1XenoLib.plugin.js:1547)
    at eval (betterdiscord://plugins/1XenoLib.plugin.js:1531)
    at Set.forEach (<anonymous>)
    at Object.setState (betterdiscord://plugins/1XenoLib.plugin.js:1531)
    at Object.show (betterdiscord://plugins/1XenoLib.plugin.js:1738)
    at Object.danger (betterdiscord://plugins/1XenoLib.plugin.js:1718)
    at Object.error (betterdiscord://plugins/1XenoLib.plugin.js:1721)
    at CrashRecovery._startFailure (betterdiscord://plugins/CrashRecovery.plugin.js:112)
    at CrashRecovery.onStart (betterdiscord://plugins/CrashRecovery.plugin.js:134)
    at CrashRecovery.onStart (betterdiscord://plugins/CrashRecovery.plugin.js:117)
    at CrashRecovery.start (betterdiscord://plugins/0PluginLibrary.plugin.js:3663)
    at Object.startPlugin (<anonymous>:4:38329)
    at Object.startAddon (<anonymous>:4:38122)
    at Object.loadAddon (<anonymous>:4:9208)
    at Object.loadAddon (<anonymous>:4:35543)
    at Object.loadAllAddons (<anonymous>:4:11288)
    at Object.initialize (<anonymous>:4:5710)
    at Object.initialize (<anonymous>:4:34738)
    at Object.startup (<anonymous>:4:392305)
(anonymous) @ 99ed9d0d194d4628b2e9.js:151
99ed9d0d194d4628b2e9.js:151 [XenoLib] Error in Notification 1307574554, screenshot or copy paste the error above to Lighty for help.
(anonymous) @ 99ed9d0d194d4628b2e9.js:151
99ed9d0d194d4628b2e9.js:151 [BetterDiscord] [WebpackModules~getModule] Module filter threw an exception. (m) => m.W.definition.label == "Client Themes" TypeError: Cannot read property 'definition' of undefined
    at eval (betterdiscord://plugins/1BunnyLib.plugin.js:528)
    at <anonymous>:4:48303
    at Function.getModule (<anonymous>:4:49246)
    at Object.getModule (<anonymous>:4:401489)
    at Function.getModule (betterdiscord://plugins/0PluginLibrary.plugin.js:2986)
    at LibraryModules.get ClientThemesExperimentModule [as ClientThemesExperimentModule] (betterdiscord://plugins/1BunnyLib.plugin.js:527)
    at eval (betterdiscord://plugins/DiscordBypasses.plugin.js:221)
    at eval (betterdiscord://plugins/DiscordBypasses.plugin.js:501)
    at eval (betterdiscord://plugins/DiscordBypasses.plugin.js:502)
    at Object.requireAddon (<anonymous>:4:37871)
    at Object.loadAddon (<anonymous>:4:8814)
    at Object.loadAddon (<anonymous>:4:35543)
    at Object.loadAllAddons (<anonymous>:4:11288)
    at Object.initialize (<anonymous>:4:5710)
    at Object.initialize (<anonymous>:4:34738)
    at Object.startup (<anonymous>:4:392305)
(anonymous) @ 99ed9d0d194d4628b2e9.js:151
0PluginLibrary.plugin.js:3101 Uncaught (in promise) TypeError: Cannot read property 'exports' of undefined
    at Function.getByIndex (0PluginLibrary.plugin.js:3101)
    at SplitLargeFiles.onStart (SplitLargeFiles.plugin.js:324)
    at SplitLargeFiles.start (0PluginLibrary.plugin.js:3663)
    at Object.startPlugin (<anonymous>:4:38329)
    at Object.startAddon (<anonymous>:4:38122)
    at Object.loadAddon (<anonymous>:4:9208)
    at Object.loadAddon (<anonymous>:4:35543)
    at Object.loadAllAddons (<anonymous>:4:11288)
    at Object.initialize (<anonymous>:4:5710)
    at Object.initialize (<anonymous>:4:34738)
    at Object.startup (<anonymous>:4:392305)
DevTools failed to load source map: Could not load content for https://discord.com/assets/99ed9d0d194d4628b2e9.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/7d4f690bcfff9ab0d122.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/bb91b842229eda7cb8e8.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/3cdf1e508a5821a0cdad.worker.js.map: Fetch through target failed: Target not supported; Fallback: Unknown error
DevTools failed to load source map: Could not load content for https://discord.com/assets/4b9659d7526aa3979710.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/a739b5da00ed40de2388.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/ee8f8635d4f89066fe0b.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/1ee95ff69c4e5d31b2b9.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/a48ac06ae30799d7d07a.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/543d7306ae64ba5afce1.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/e52a1aba0da21fd722a0.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/19a1dea9e421358897b9.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/766cf625546df87be871.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/f0f7f1921824539dd4a9.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/975aba216feae213687f.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/eb27dd7912ec0c101f4a.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/12229a0fe8aec68d443e.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/9e2273041e0d402b5480.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/4e5ff9264802ba2e0075.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/448fa50b11e0d3c5565b.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/c8e491b27fe94f60d363.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/e837a0c6d7b71a4e34b5.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/2bca5148146ab09a0f77.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/c30dc89c64400a4d4e76.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/4d35867b89d391765d7f.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/310a10d7659148f7e21e.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/b62c62429a41fb1f5911.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/62d286b17af9dc3e0530.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/db95a9b696fc7c2590ae.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/018e57645911f57b4f3a.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/4ff4d2a5c762a2b1c7bd.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/6711a2d181d475a23422.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/495f481a29a0e8386942.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/c9ee238023dd6396cbbe.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/8c2d153a10930a8ca299.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/b40679c0d82dac77d8bc.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/95cfc4cef4d0837344fe.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/4fbc91c6c5ac39511bb3.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/efc8d991b35964861734.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/1587e1f8a871cc0b9d58.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/3c2cf1ee2b629200e3ce.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/77b0410a447c334d3fc2.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/cb55214b1d3b43b20ce4.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/fd1f4b8aa353aae0c6be.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/ff53f20b689e441f2cb2.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/8c78a99552d0760f0dac.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/3b54352e8b3452d413e2.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/79226e60c979f811ea95.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/fabe5167f413a48cbbe1.worker.js.map: Fetch through target failed: Target not supported; Fallback: Unknown error
DevTools failed to load source map: Could not load content for https://discord.com/assets/81f6996439434ddae868.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/86890f3d439b93d6d4ac.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/7a9ff6166efc70c82b2c.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/e5d70fa752ebc1e71192.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/d6d39d56197e55d35da8.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/4c5753c555bf42d3ccf9.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/343e0d1010908d294d85.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/40532.45cfda0794123b4bec3c.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/bd46a31e0538d73573d2.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/ac5a2ca155ef07ea4050.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://discord.com/assets/12a48ce31802b7fd8315.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
99ed9d0d194d4628b2e9.js:151 Error: Menu API only allows Items and groups of Items as children. Received function kc(e){return null} (object) instead
    at 4b9659d7526aa3979710.js:2844
    at Array.reduce (<anonymous>)
    at ko (4b9659d7526aa3979710.js:2842)
    at jo (4b9659d7526aa3979710.js:2846)
    at eval (0BDFDB.plugin.js:2871)
    at Sa (4b9659d7526aa3979710.js:1651)
    at yu (4b9659d7526aa3979710.js:1705)
    at Oc (4b9659d7526aa3979710.js:1698)
    at Ic (4b9659d7526aa3979710.js:1698)
    at hc (4b9659d7526aa3979710.js:1697)
    at uc (4b9659d7526aa3979710.js:1694)
    at Fo (4b9659d7526aa3979710.js:1634)
    at lc (4b9659d7526aa3979710.js:1695)
    at 4b9659d7526aa3979710.js:1714
    at el (4b9659d7526aa3979710.js:1714)
    at Object.t.render (4b9659d7526aa3979710.js:1718)
    at Proxy.MyReact.render (0BDFDB.plugin.js:2855)
    at Proxy.MyReact.hookCall (0BDFDB.plugin.js:2870)
    at loadLibrary (0BDFDB.plugin.js:7769)
    at parseData (0BDFDB.plugin.js:1155)
    at parseCSS (0BDFDB.plugin.js:1117)
    at requestLibraryData (0BDFDB.plugin.js:1160)
    at eval (0BDFDB.plugin.js:1107)
    at args.<computed> (0BDFDB.plugin.js:190)
    at Function.<anonymous> (<anonymous>:4:344769)
(anonymous) @ 99ed9d0d194d4628b2e9.js:151
r.<computed> @ 4b9659d7526aa3979710.js:8922
ds @ 4b9659d7526aa3979710.js:1659
n.callback @ 4b9659d7526aa3979710.js:1660
Bi @ 4b9659d7526aa3979710.js:1641
Tu @ 4b9659d7526aa3979710.js:1690
Ou @ 4b9659d7526aa3979710.js:1689
mu @ 4b9659d7526aa3979710.js:1689
(anonymous) @ 4b9659d7526aa3979710.js:1700
vc @ 4b9659d7526aa3979710.js:1701
uc @ 4b9659d7526aa3979710.js:1695
Fo @ 4b9659d7526aa3979710.js:1634
lc @ 4b9659d7526aa3979710.js:1695
(anonymous) @ 4b9659d7526aa3979710.js:1714
el @ 4b9659d7526aa3979710.js:1714
t.render @ 4b9659d7526aa3979710.js:1718
MyReact.render @ 0BDFDB.plugin.js:2855
MyReact.hookCall @ 0BDFDB.plugin.js:2870
loadLibrary @ 0BDFDB.plugin.js:7769
parseData @ 0BDFDB.plugin.js:1155
parseCSS @ 0BDFDB.plugin.js:1117
requestLibraryData @ 0BDFDB.plugin.js:1160
eval @ 0BDFDB.plugin.js:1107
args.<computed> @ 0BDFDB.plugin.js:190
(anonymous) @ VM461:4
(anonymous) @ VM88 C:\Users\X-File\AppData\Roaming\BetterDiscord\data\betterdiscord.asar\preload.js:1
emit @ VM14 events.js:327
endReadableNT @ VM81 readable.js:1327
processTicksAndRejections @ VM24 task_queues.js:80
```

**Comment by Davilarek** [comment]
there was a feature like this? sorry I don't remember

**Comment by XspeedPL** [comment]
Usually there would be a context menu item for MLV2 functions, but it's clearly missing on the screenshot

**Comment by surya27895** [comment]
I also forget about it, but in the old config file I have backed up there is some channel ID listed, so i assumse it exist before

**Comment by Davilarek** [comment]
I'm sorry. I didn't notice. You all are right, there was this feature, Discord renamed gdm context to channel context. Fix is going to be released soon.

**Comment by Davilarek** [comment]
No, it wasn't that, it seems Lighty purposely removed channel logs, however I have no idea why. Maybe it crashes or something. Needs bug testing.
db096e8
